import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import Sidebar from '@/components/layout/Sidebar';
import { ModalProvider } from '@/contexts/ModalContext';
import Modal from '@/components/modals/Modal';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ModalProvider>
          <div className="min-h-screen bg-zinc-50 text-zinc-900 dark:bg-black dark:text-zinc-100">
            <div className="mx-auto flex w-full gap-0">
              <Sidebar />
              <main className="flex-1 px-6 py-8">{children}</main>
            </div>
          </div>
          <Modal />
        </ModalProvider>
      </body>
    </html>
  );
}
